CREATE DATABASE cat

USE cat

CREATE TABLE USER(
id INT PRIMARY KEY,
PASSWORD VARCHAR(32) NOT NULL
);

CREATE TABLE reporter(
id VARCHAR(32),
PASSWORD VARCHAR(32)
);

CREATE TABLE news(
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(256),
content1 MEDIUMTEXT,
img1 VARCHAR(32),
content2 MEDIUMTEXT,
img2 VARCHAR(32),
content3 MEDIUMTEXT,
img3 VARCHAR(32),
reporter VARCHAR(32),
COUNT INT DEFAULT 0,
TYPE VARCHAR(16)
);

CREATE TABLE COMMENT(
id INT PRIMARY KEY AUTO_INCREMENT,
USER VARCHAR(32),
news INT,
content VARCHAR(256) NOT NULL,
TIME VARCHAR(32)
);